### ISSUE TITLE
ECG API MODEL

### ISSUE THREAD

**Issue by Josecisneros001** [Josecisneros001/ibm-challenge#6]
**Comportamiento deseado**
- Obtener API del modelo funcional.

**Tasks** 
- [ ] Organizar DataSet
- [ ] Documentar Algoritmo Seleccionado
- [ ] Crear Modelo para la predicción del ECG con Watson.
- [ ] API probada con curl o con el navegodor JS.
