### ISSUE TITLE
Visual Recognition API MODEL 

### ISSUE THREAD

**Issue by Josecisneros001** [Josecisneros001/ibm-challenge#7]
**Comportamiento deseado**
- Obtener API del modelo funcional.

**Tasks** 
- [ ] Organizar DataSet
- [ ] Documentar Algoritmo Seleccionado
- [ ] Crear Modelo para la predicción de enfermedades con radiografías usando Watson.
- [ ] API probada con curl o con el navegodor JS.
